version: "3.3"

services:
  app:
    image: ${DTR_URL:-dtr.demo.dckr.org}/demo/docker-demo:${TAG:-latest}
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 2
        delay: 5s
        failure_action: continue
      labels:
        - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT:-dev}"
        - "com.docker.lb.hosts=docker-demo-${ENVIRONMENT:-dev}.${DOMAIN_NAME:-demo.dckr.org}"
        - "com.docker.lb.port=8080"
        - "com.docker.lb.network=docker-demo-${ENVIRONMENT:-dev}_docker-demo"
    environment:
      - "TITLE=Docker Demo-${ENVIRONMENT:-dev} on Swarm mode"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_NAME=${DB_NAME:-demo}"
      - "DB_SSL_MODE=disable"
    secrets:
      - source: DB_USER
        target: DB_USER
        uid: "0"
        gid: "0"
        mode: 0400
      - source: DB_PASS
        target: DB_PASS
        uid: "0"
        gid: "0"
        mode: 0400
    networks:
      - docker-demo
  db:
    image: ${DTR_URL:-dtr.demo.dckr.org}/official/postgres:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT:-dev}"
    environment:
      - "POSTGRES_USER_FILE=/run/secrets/DB_USER"
      - "POSTGRES_PASSWORD_FILE=/run/secrets/DB_PASS"
    secrets:
      - source: DB_USER
        target: DB_USER
        uid: "999"
        gid: "999"
        mode: 0400
      - source: DB_PASS
        target: DB_PASS
        uid: "999"
        gid: "999"
        mode: 0400
    volumes:
      - /shared/postgres/swarm/${ENVIRONMENT:-dev}:/var/lib/postgresql/data
    networks:
      - docker-demo

networks:
  docker-demo:
    driver: overlay
    labels:
      - "com.docker.ucp.access.label=/demo-collection/${ENVIRONMENT:-dev}"

secrets:
  DB_USER:
    external:
      name: ${ENVIRONMENT:-dev}_DB_USER
  DB_PASS:
    external:
      name: ${ENVIRONMENT:-dev}_DB_PASS
